server:
  port: 8081

spring:
  application:
    name: link-shortener
  cloud:
    discovery:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info

db:
  url: jdbc:postgresql://localhost:5432/links_db