server:
  port: 8081

spring:
  application:
    name: link-create-service
  cloud:
    discovery:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
