server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: link-create-service
          uri: http://localhost:8081
          predicates:
            - Path=/link/**

    discovery:
      locator:
        enabled: true
