apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-shortener
  template:
    metadata:
      labels:
        app: link-shortener
    spec:
      containers:
        - name: link-shortener
          image: link-shortener
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: link-shortener-service
spec:
  selector:
    app: link-shortener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
